site:
  title: "OpenCPN Inland ECDIS Manual"
  url: https://opencpn-manuals.github.io/inland-ecdis/
  start_page: en@manuals:ROOT:index.adoc

urls:
  html_extension_style: indexify
asciidoc:
  attributes:
    icons: font
antora:
  extensions:
  - require: ./src-list.js
    trace: true
    languages: [en, fr, de, nl]  
    
content:
  edit_url: true
  sources:
  - url: https://github.com/opencpn-manuals/inland-ecdis-docs.git
    start_paths:
      - fr
      - en
      - de
      - nl
      
    branches:
      - main
      

ui:
  bundle:
    url: ./ui-bundle.zip
    #snapshot: true
    #url: ../antora-ui-default/build/ui-bundle.zip
    #supplemental_files: ./node_modules/@antora/lunr-extension/supplemental_ui
  supplemental_files: ./supplemental_ui
output:
  dir: ./public

runtime:
  fetch: true
  log:
    format: pretty
    level: info
